### ISSUE TITLE
subprocess32 fails to compile on Python 2.6.6

### ISSUE THREAD

**Issue by jayvdb** [ogrisel/python-appveyor-demo#16]
Subprocess32 appears to be a fairly normal Extension (https://github.com/christopherobin/python-subprocess32/blob/master/setup.py), however it fails on 2.6.6:
https://ci.appveyor.com/project/jayvdb/python-appveyor-demo/build/job/np7rxolx71fwnegb

So maybe there is more to 2.6.6 support than simply https://github.com/ogrisel/python-appveyor-demo/pull/11 .

**Comment by jayvdb** [comment]
Maybe distutils.core on Python 2.6.6 is to blame.
I'll try switching it to using setuptools.

**Comment by ogrisel** [comment]
Have you tried to reproduce the issue on a Windows VM? It's probably note related to appveyor.

**Comment by jayvdb** [comment]
Yea, sorry, unistd.h doesnt exist on Windows.
