### ISSUE TITLE
do we still need to configure SDK for Python27-x64?

### ISSUE THREAD

**Issue by anthrotype** [ogrisel/python-appveyor-demo#39]
As you know, the PyPA "Packaging User Guide" has a page on "Supporting Windows using Appveyor":
http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/
https://github.com/pypa/python-packaging-user-guide/blob/master/source/appveyor.rst

In their guide, as well as in the example `build.cmd` batch script that they provide, they pass specific Windows SDK environment variables only for **Python 3.3 and 3.4 (64-bit)**, and *not* also for **Python 2.7 64-bit** as it's recommended here in this demo repository.

> Appveyor includes by default all of the compiler toolchains needed to build extensions for Python. For Python 2.7, 3.5+ and 32-bit versions of 3.3 and 3.4, the tools work out of the box. But for 64-bit versions of Python 3.3 and 3.4, there is a small amount of additional configuration needed to let distutils know where to find the 64-bit compilers. (From 3.5 onwards, the version of Visual Studio used includes 64-bit compilers with no additional setup).

So now I wonder who's right... Perhaps has something changed on Appveyor setup that it no longer requires us to configure environment when building extension for Python 2.7 with MSVC on a 64bit architecture?

**Comment by ogrisel** [comment]
I am not sure. If you feel like running experiments please report your results here so as to update the documentation.

**Comment by anthrotype** [comment]
I tried disabling the `run_with_cmd.cmd` script and run the Python27-x64 build on Appveyor. Even without the `DISTUTILS_USE_SDK=1` etc., it is picking up the correct `amd64` version of Visual C++ compiler:

https://ci.appveyor.com/project/anthrotype/python-appveyor-demo/build/1.0.1/job/7ih1muhv0tea0beu#L130

**Comment by anthrotype** [comment]
yes, only 3.3 and 3.4 (both 64 bit) fail when run without the correct environment setup:
https://ci.appveyor.com/project/anthrotype/python-appveyor-demo/build/1.0.2

**Comment by ogrisel** [comment]
Alright I understand: setuptools automatically picked up [Visual C++ for Python](https://www.microsoft.com/en-us/download/details.aspx?id=44266). However that will only work for projects that builds their extension using a recent version of setuptools. Other projects that only use distutils or a patched version of distutils might fail (for instance I suspect that building numpy this way would not work although I have not tested).

https://ci.appveyor.com/project/anthrotype/python-appveyor-demo/build/1.0.2/job/hmaya7suq3lwl2f2#L118

**Comment by anthrotype** [comment]
I see. Thanks for the clarification!

**Comment by ogrisel** [comment]
I think we can close this issue. Both versions are right (it depends if you use setuptools to build the compiled extensions of your Python project or not).
