### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by rhyolight** [ogrisel/python-appveyor-demo#5]
This is really useful. Many thanks for putting it online. It's especially nice for us non-Windows users trying to get python projects working in AppVeyor. 

![You Win](http://img4.wikia.nocookie.net/__cb20120507005835/mlp/images/9/92/Hub_Promo_-_8_bit_commercial_You_Win.png)

**Comment by ogrisel** [comment]
Glad to help :)

**Comment by stonebig** [comment]
+1 for your pycon2015 conference!

**Comment by hickford** [comment]
Thanks too
