### ISSUE TITLE
Configuring Appveyor online?

### ISSUE THREAD

**Issue by paulmueller** [ogrisel/python-appveyor-demo#6]
When I give appveyor.com this git repository ( https://github.com/ogrisel/python-appveyor-demo.git ) then I get the following error:

    Build started
    git clone -q --branch=master https://github.com/ogrisel/python-appveyor-demo.git C:\projects\python-appveyor-demo
    Specify a project or solution file. The directory does not contain a project or solution file.

Do I have to edit settings online at appveyor.com in order for the build to work?

Here is the project page page on appveyor.com: https://ci.appveyor.com/project/paulmueller/python-appveyor-demo

Thanks for the info,
Paul

**Comment by paulmueller** [comment]
I have managed to make the build "pass" by explicitly setting the build to "off" in the online settings. However, I have the feeling that the appveyor.yml configuration is not used:

    Build started
    git clone -q --branch=master https://github.com/ogrisel/python-appveyor-demo.git C:\projects\python-appveyor-demo
    Discovering tests...OK
    Build success

Any hint?

**Comment by paulmueller** [comment]
Got it. This seems to be a problem with Appveyor. One needs to add the project with the "GitHub" option.

http://help.appveyor.com/discussions/problems/1513-appveyoryml-is-ignored

[In] "generic" Git and Mercurial provider implementation appveyor.yml is not supported.

**Comment by ogrisel** [comment]
Glad you found the fix for your issue and thanks for reporting the solution here. Hopefully that will make it easier for others to google it.
