### ISSUE TITLE
Minor release numbers are not consistent on https://www.python.org/ftp/python/

### ISSUE THREAD

**Issue by jayvdb** [ogrisel/python-appveyor-demo#9]
Installing 2.7.0 fails because the release directory is

https://www.python.org/ftp/python/2.7/

instead of

https://www.python.org/ftp/python/2.7.0/

Note that from 3.3 onwards, the directory does include '.0'

https://www.python.org/ftp/python/3.3.0/

**Comment by jayvdb** [comment]
A nice solution is to show the user the problem (this is a demo after all) by adding two more builds to the matrix, using "2.7" and "2.7.1" as the labels with a link to this ticket.  That will slow down the builds of this project, and I dont think it is as easily justified as the extra build for 2.6.6.

I guess doing "3.0" and "3.0.1" releases are a better candidate for extra builds, as 3.0 is a dogs breakfast, but nobody typically needs to build against it.  Having it in the build matrix might let people easily see that their project fails on 3.0 and they cant simply state they support Python 3+

Or install.ps1 could detect "2.7.0" and download using "2.7" instead; likewise for "3.0", "3.1" and "3.2".

Due to issue #10 , there isnt much point in detecting "2.6.0".

**Comment by ogrisel** [comment]
> Or install.ps1 could detect "2.7.0" and download using "2.7" instead; likewise for "3.0", "3.1" and "3.2".

I think would be great.
